require_relative '../node_modules/react-native/scripts/cocoapods/autolinking.rb'

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

$RNFirebaseAsStaticFramework = true
use_frameworks! :linkage => :static

target 'skyborne' do
  config = use_native_modules!

  use_react_native!(
    :path => "../node_modules/react-native",
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'skyborneTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # scripts/react_native_pods.rb
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    # Fix fmt library C++ compilation issues
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |bc|
        bc.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        bc.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
        bc.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
        bc.build_settings['CLANG_WARN_NON_MODULAR_INCLUDE_IN_FRAMEWORK_MODULE'] = 'NO'
      end

      if target.name == 'fmt'
        target.build_configurations.each do |bc|
          bc.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
          cppflags = bc.build_settings['OTHER_CPLUSPLUSFLAGS'] || '$(inherited)'
          cppflags = cppflags.join(' ') if cppflags.is_a?(Array)
          unless cppflags.include?('-DFMT_USE_CONSTEVAL=0')
            cppflags = "#{cppflags} -DFMT_USE_CONSTEVAL=0".strip
          end
          bc.build_settings['OTHER_CPLUSPLUSFLAGS'] = cppflags
        end
      end
    end

    installer.aggregate_targets.each do |aggregate_target|
      user_project = aggregate_target.user_project
      user_project.native_targets.each do |native_target|
        native_target.build_configurations.each do |bc|
          bc.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
          bc.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
          bc.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
          bc.build_settings['CLANG_WARN_NON_MODULAR_INCLUDE_IN_FRAMEWORK_MODULE'] = 'NO'
        end
      end
      user_project.save
    end
    
    installer.pods_project.save
  end
end
